execute as @e[type=item,name="Земля"] run tp @s @p[tag=player:tp_ore,scores={lvl=1..1}]
execute as @e[type=item,name="Булыжник"] run tp @s @p[tag=player:tp_ore,scores={lvl=2..2}]
execute as @e[type=item,name="Уголь"] run tp @s @p[tag=player:tp_ore,scores={lvl=3..4}]
execute as @e[type=item,name="Сырое железо"] run tp @s @p[tag=player:tp_ore,scores={lvl=5..5}]
execute as @e[type=item,name="Сырая медь"] run tp @s @p[tag=player:tp_ore,scores={lvl=6..7}]
execute as @e[type=item,name="Редстоун"] run tp @s @p[tag=player:tp_ore,scores={lvl=8..9}]
execute as @e[type=item,name="Сырое золото"] run tp @s @p[tag=player:tp_ore,scores={lvl=10..10}]
execute as @e[type=item,name="Лазурит"] run tp @s @p[tag=player:tp_ore,scores={lvl=11..12}]
execute as @e[type=item,name="Алмаз"] run tp @s @p[tag=player:tp_ore,scores={lvl=13..14}]
execute as @e[type=item,name="Изумруд"] run tp @s @p[tag=player:tp_ore,scores={lvl=15..15}]
execute as @e[type=item,name="Незерак"] run tp @s @p[tag=player:tp_ore,scores={lvl=16..16}]
execute as @e[type=item,name="Блок магмы"] run tp @s @p[tag=player:tp_ore,scores={lvl=17..17}]
execute as @e[type=item,name="Кварц"] run tp @s @p[tag=player:tp_ore,scores={lvl=18..18}]
execute as @e[type=item,name="Золотой самородок"] run tp @s @p[tag=player:tp_ore,scores={lvl=19..19}]
execute as @e[type=item,name="Древние обломки"] run tp @s @p[tag=player:tp_ore,scores={lvl=20..21}]
execute as @e[type=item,name="Незеритовый блок"] run tp @s @p[tag=player:tp_ore,scores={lvl=22..23}]
execute as @e[type=item,name="Обсидиан"] run tp @s @p[tag=player:tp_ore,scores={lvl=24..24}]
execute as @e[type=item,name="Плачущий обсидиан"] run tp @s @p[tag=player:tp_ore,scores={lvl=25..25}]
execute as @e[type=item,name="Осколок аметиста"] run tp @s @p[tag=player:tp_ore,scores={lvl=26..26}]
