execute as @e[type=item,name="Dirt"] run tp @s @p[tag=player:tp_ore,scores={lvl=1..1}]
execute as @e[type=item,name="Cobblestone"] run tp @s @p[tag=player:tp_ore,scores={lvl=2..2}]
execute as @e[type=item,name="Coal"] run tp @s @p[tag=player:tp_ore,scores={lvl=3..4}]
execute as @e[type=item,name="Raw Iron"] run tp @s @p[tag=player:tp_ore,scores={lvl=5..5}]
execute as @e[type=item,name="Raw Copper"] run tp @s @p[tag=player:tp_ore,scores={lvl=6..7}]
execute as @e[type=item,name="Redstone"] run tp @s @p[tag=player:tp_ore,scores={lvl=8..9}]
execute as @e[type=item,name="Raw Gold"] run tp @s @p[tag=player:tp_ore,scores={lvl=10..10}]
execute as @e[type=item,name="Lapis"] run tp @s @p[tag=player:tp_ore,scores={lvl=11..12}]
execute at @e[type=item,name="Diamond"] run tp @s @p[tag=player:tp_ore,scores={lvl=13..14}]
execute as @e[type=item,name="Emerald"] run tp @s @p[tag=player:tp_ore,scores={lvl=15..15}]
execute as @e[type=item,name="Netherrack"] run tp @s @p[tag=player:tp_ore,scores={lvl=16..16}]
execute as @e[type=item,name="Magma Block"] run tp @s @p[tag=player:tp_ore,scores={lvl=17..17}]
execute as @e[type=item,name="Quartz"] run tp @s @p[tag=player:tp_ore,scores={lvl=18..18}]
execute as @e[type=item,name="Golden Nugget"] run tp @s @p[tag=player:tp_ore,scores={lvl=19..19}]
execute as @e[type=item,name="Ancient Debris"] run tp @s @p[tag=player:tp_ore,scores={lvl=20..21}]
execute as @e [type=item,name="Netherite Block"] run tp @s @p[tag=player:tp_ore,scores={lvl=22..23}]
execute as @e[type=item,name="Obsidian"] run tp @s @p[tag=player:tp_ore,scores={lvl=24..24}]
execute as @e[type=item,name="Crying Obsidian"] run tp @s @p[tag=player:tp_ore,scores={lvl=25..25}]
execute as @e[type=item,name="Amethyst Shard"] run tp @s @p[tag=player:tp_ore,scores={lvl=26..26}]
